#!/bin/bash

BINDDIRS="dev tmp"

. chroots-functions

function usage {

NAME=`echo $1 | sed -e "s/\.\///g"`

cat << EOF
usage: $NAME COMMAND

  Mount the necessary partitions to start the specified chroot.

OPTIONS:
    -h, --help    Show this message
    -v, --verbose Verbose output
EOF
    exit 0;
}



OPTS="vh"
LONGOPTS="verbose,help"
TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

if [ $? != 0 ]; then
	echo "Invalid arguments";
	usage $0;
	exit 1 ;
fi

eval set -- "$TEMP"


while true; do
	case "$1" in
		--help|-h)
			usage $0;
			exit 0;
			shift;
			;;
		--verbose|-v)
			VERBOSE=1
			shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

chroots_check_permissions;

# Check input and select a chroot

get_work_chroot $1

CHRNAME=$_CHRNAME

chroots_verify_chroot $CHRNAME;

if [ $? != 0 ]; then
	exit 1;
fi;

# Find the necessary mount points and verify

chroots_check_mount $CHRNAME;

if [ $? != 0 ]; then
	echo "Chroot \"$CHRNAME\" already mounted."
	exit 1;
fi;

# Mount

CHRTARGET=$_CHRTARGET

if [ $VERBOSE == 1 ]; then
	echo "Mount proc dir $CHRTARGET/proc"
fi;

mount -t proc none $CHRTARGET/proc

for i in $BINDDIRS; do
	if [ $VERBOSE == 1 ]; then
		echo "Binding /$i to $CHRTARGET/$i"
	fi;
	mount -o bind /$i $CHRTARGET/$i
done;
