#!/bin/bash

. chroots-functions

CONF="$HOME/.chroots"

CHECK=0
CLEAN=0

# temporaty PATH workaround
PATH=$PATH:.
CHROOTS_DELETE=`which chroots-delete`
if [ -z $CHROOTS_DELETE ]; then
	echo "Couldn't find chroots-delete in PATH"
fi;

function usage {
NAME=`echo $1 | sed -e "s/\.\///g"`

	cat << EOF
 $NAME list
 Usage example: $NAME list

OPTIONS:
  -h, --help           Show this message
  -v, --verbose        Verbose mode
  -c, --check          Check the validity of listed chroots
  -C, --clean          Remove failed chroots
EOF
}

# Begin program

OPTS="vhcC"
LONGOPTS="verbose,help,check,clean"

TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

if [ $? != 0 ] ; then
	usage $0;
	exit 1;
fi

eval set -- "$TEMP"

while true;  do
	case "$1" in
		--help|-h)
			usage $0
			exit 0
			;;
		--check|-c)
			CHECK=1
			echo "Checking valid chroots"
			shift;
			;;
		--clean|-C)
			CLEAN=1
			echo "Removing any failed chroots"
			shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

if [ ! -r $CONF ]; then
	exit 0
fi;

NL=`cat $CONF | grep -v "^#" | wc -l`

echo "total $NL"

echo "#  Name   Path   Distro   Default user"

let i=0
while read line; do
	T=`echo $line | grep -v "^#"`
	if [ "$T" == "" ]; then
		continue;
	fi;
	let i=$i+1
	echo "$i: $line"

	if [ $CHECK == 1 ]; then
		CHRNAME=`echo $line | cut -d " " -f 1`

		chroots_verify_chroot $CHRNAME;

		if [ $? != 0 ]; then
			echo "Invalid chroot $CHRNAME."
			if [[ $CLEAN == 1 || -x $CHROOTS_DELETE ]]; then
				$CHROOTS_DELETE $CHRNAME
			fi;
		else
			echo "Chroot $CHRNAME is OK"
		fi;
	fi;

done < "$CONF"

exit 0
