#!/bin/bash

. chroots-functions

FORCE=0

function usage {

NAME=`echo $1 | sed -e "s/\.\///g"`

	cat << EOF
 $NAME [target] [OPTIONS]"
 Usage example: $NAME hardy"

  Unmount the specified chroot.

OPTIONS:
  -h, --help      Show this message
  -v, --verbose   Verbose
  -f, --force     Force umounting the shared paths

EOF
exit 0
}

OPTS="vhf"
LONGOPTS="verbose,help,force"
TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

eval set -- "$TEMP"

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true; do
	case "$1" in
		--help|-h)
			usage $0;
			exit 0;
			shift;
			;;
		--verbose|-v)
			VERBOSE=1
			shift;
			;;
		--force|-f)
			FORCE=1;
			shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

chroots_check_permissions

# Determine chroot to use

if [ "$1" == "" ]; then
	get_default_chroot;
	CHRNAME=$DEFAULT_CHRNAME
else
	CHRNAME=$1;
fi;

# Validate chroot

if [ $FORCE == 0 ];  then
	chroots_check_mount $CHRNAME

	if [ $? != 1 ]; then
		echo "Chroot $CHRNAME is not mounted.";
		exit 1;
	fi;

else
	echo "Forcing unmount chroot $CHRNAME";
fi;

# Try to unmount

if [ $VERBOSE == 1 ]; then
	echo "Stoping chroot $CHRNAME running on $_CHRTARGET";
fi;

for i in proc dev tmp; do
	if [ $VERBOSE == 1 ]; then
		echo "Unmounting $_CHRTARGET/$i";
	fi;

	umount $_CHRTARGET/$i &>/dev/null

	if [ $? != 0 ]; then
		echo "Failed to umount $_CHRTARGET/$i";
	fi;
done;
