#!/bin/bash

. chroots-functions

CHRUSER=""

function usage {

NAME=`echo $1 | sed -e "s/\.\///g"`

	cat << EOF
 $NAME [chroot_name] [OPTIONS]"
 Usage example: $NAME hardy "

  Login to the specified chroot, which can be listed with "chroots list".

OPTIONS:
  -h, --help      Show this message
  -v, --verbose   Verbose output
  -u, --username  Use a specific username to login

EOF
exit 0
}

OPTS="vhu:"
LONGOPTS="verbose,help,username:"
TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

eval set -- "$TEMP"

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true; do
	case "$1" in
		--help|-h)
			usage $0;
			exit 0;
			shift;
			;;
		--verbose|-v)
			VERBOSE=1
			shift;
			;;
		--username|-u)
			CHRUSER=$2;
			shift; shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

chroots_check_permissions;

# Determine chroot to use

get_work_chroot $1;

CHRNAME=$_CHRNAME;

if [ $VERBOSE == 1 ]; then
	echo "Using $CHRNAME as chroot name"
fi;

# Validate chroot
chroots_check_mount $CHRNAME 

if [ $? != 1 ]; then
	echo "chroot $CHRNAME is not mounted or does not exist."
	exit 1;
fi;

# Select user to use
if [ "$CHRUSER" == "" ]; then
	echo "Using default user $_CHRUSER"
	CHRUSER=$_CHRUSER
fi;

# Login

if [ $VERBOSE == 1 ]; then
	echo "Loging in to $CHRUSER@$CHRNAME"
fi;

chroot $_CHRTARGET /bin/su - $CHRUSER
