#!/bin/bash

function usage {

NAME=`echo $1 | sed -e "s/\.\///g"`

cat << EOF
usage: $NAME COMMAND

The most commonly used chroots commands are:
    setup   Bootstrap a basic debian system
    list    List existing chroots installed with chroots
    init    Mount/Bind the necessary paths to be used in the chroot
    login   Login to chroot
    stop    Unmount/Unbind the previously mounted chroot paths

OPTIONS:
    -h, --help    Show this message
    -v, --verbose Verbose output
EOF
    exit 0;
}

VERBOSE=0

OPTS="+vh"
LONGOPTS="verbose,help"

TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

if [ $? != 0 ] ; then
	echo "Invalid arguments.";
	usage $0;
	exit 1 ;
fi;

eval set -- "$TEMP"


while true; do
	case "$1" in
		--help|-h)
			usage $0;
			exit 0;
			shift;
			;;
		--verbose|-v)
			VERBOSE=1
			shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

case "$1" in 
    "setup"|"init"|"login"|"stop"|"list"|"delete")
	CMD=$1
	shift;

	PATH=$PATH:.
        CHROOTS_PATH=`which chroots-$CMD`
        if [ -z $CHROOTS_PATH ]; then
            echo "Couldn't find chroots-$CMD in PATH"
            exit 1
        else
		$CHROOTS_PATH $@
		exit 0
	fi
        ;;
    *)
        usage $0
        ;;
esac
