#!/bin/bash
#
# Copyright (C) 2008  Alfredo Matos
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>
#

function chroots_check_permissions {
	if [ $UID != 0 ]; then
		echo "Superuser permissions required. Aborting."
		exit 1
	fi;
}

function chroots_version {
	echo "$PROGNAME $PROGVERSION - Copyright (C) Alfredo Matos 2008"
}

function get_work_chroot {
	if [ "$1" == "" ]; then
        	get_default_chroot;
	        echo "Using default chroot $DEFAULT_CHRNAME";
        	_CHRNAME=$DEFAULT_CHRNAME;
	else
        	_CHRNAME=$1;
	fi;
}

function get_default_chroot {
	if [ -r /etc/lsb-release ]; then
		. /etc/lsb-release
		DEFAULT_CHRNAME=$DISTRIB_CODENAME
	else
		DEFAULT_CHRNAME=hardy
	fi;
}

function chroots_get_target {
	_CHRNAME=$1
	_CHRTARGET=$2
	if [ "$_CHRTARGET" == "" ]; then
		_CHRTARGET=/var/chroots
		_CHRPATH=$_CHRTARGET/$_CHRNAME
		echo "Using default chroot target: \"$_CHRPATH\""
	fi;
}

function chroots_get_chroot {
	if [ ! -f $CHROOTS ]; then
		echo "File $CHROOTS does not exist. No chroot installed.";
		return 1;
	fi;

	CFG=`grep "^$1 " $CHROOTS` 

	if [ "$CFG" == "" ]; then
		if [ $VERBOSE == 1 ]; then
			echo "$1 does no exist in $CHROOTS"
		fi;
		return 1;
	fi;

	_CHRTARGET=`echo $CFG | cut -d " " -f 2`
	_CHRDISTRO=`echo $CFG | cut -d " " -f 3`
	_CHRUSER=`echo $CFG | cut -d " " -f 4`
	_CHRNAME=$1

	return 0;
}

function __chroots_check_mount {
	DEV=$1
	TARGET=$2

	MOUNTOUTPUT=`mount | grep "^$DEV on $TARGET"`

	if [ "$MOUNTOUTPUT" != "" ]; then
		return 1;
	fi;

	return 0;
}

function chroots_verify_chroot {

	if [ $VERBOSE == 1 ]; then
		echo "Verifying chroot $1"
	fi;

	chroots_get_chroot $1;

	if [ $? != 0 ]; then
		echo "Mount check failed because $1 does not exist"
		return 2;
	fi;

	if [ ! -d $_CHRTARGET ]; then
		echo "Chroot target $_CHRTARGET not found."
		echo "Perhaps you should delete and install the chroot again."
		return 1;
	fi;

	return 0;
}

function chroots_check_mount {

	chroots_verify_chroot $1

	if [ $? != 0 ]; then
		return $?;
	fi;

	if [ $VERBOSE == 1 ]; then
		echo "Checking if $_CHRNAME is mounted..."
	fi;

	__chroots_check_mount "none" "$_CHRTARGET/proc"
	PROCMOUNT=$?

	__chroots_check_mount "/dev" "$_CHRTARGET/dev"
	DEVMOUNT=$?

	__chroots_check_mount "/tmp" "$_CHRTARGET/tmp"
	TMPMOUNT=$?

	if [ $VERBOSE == 1 ]; then
		if [ $PROCMOUNT == 0 ]; then
			echo "$_CHRTARGET/proc is not mounted"
		fi;

		if [ $DEVMOUNT == 0 ]; then
			echo "$_CHRTARGET/dev is not mounted"
		fi;

		if [ $TMPMOUNT == 0 ]; then
			echo "$_CHRTARGET/tmp is not mounted"
		fi;
	fi;

	if [[ $PROCMOUNT == 1 || $DEVMOUNT == 1 || $TMPMOUNT == 1 ]]; then
		return 1;
	fi;

	return 0;
}

function chroots_check_dir {
	DIR=$1
	# echo "Checking $DIR"
	if [ ! -d $DIR ]; then
		echo "$DIR does not exist. Creating it."
		mkdir -p $DIR
		if [ $? != 0 ]; then
			echo "error creating $DIR. Aborting"
			exit 1
		fi;
	fi;
}
