#!/bin/bash

MIRROR="http://archive.ubuntu.com/ubuntu"
DEBOOTSTRAP=/usr/sbin/debootstrap

function usage {
NAME=`echo $1 | sed -e "s/\.\///g"`

	cat << EOF
 $NAME [distribution destination]
 Usage example: $NAME hardy /var/chroot/test-hardy

OPTIONS:
  -h, 	       --help    		Show this message
  -v,          --verbose 		Verbose
  -u USERNAME, --user USERNAME          Copy a user from the system 
  -g GROUP,    --group GROUPNAME        Copy a group from the system
  -c,          --no-cache               Do not use the package cache

EOF
}

function check_dir {
	DIR=$1
	echo "Checking $DIR"
	if [ ! -d $DIR ]; then
		echo "$DIR does not exist. Creating it."
		mkdir -p $DIR
		if [ $? != 0 ]; then
			echo "error creating $DIR. Aborting"
			exit 1
		fi;
	fi;
}


# Begin program

VERBOSE=0
USECACHE="yes"

# determine user and GROUP

CHRUSER=$USER
CHRGROUP=$GROUPS

if [ $SUDO_USER ]; then
	CHRUSER=$SUDO_USER
	CHRGROUP=$SUDO_GID
fi;

OPTS="vhu:g:c"
LONGOPTS="verbose,help,user:,group:,no-cache"

TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

eval set -- "$TEMP"

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true; do
	case "$1" in
		--help|-h)
			usage $0;
			shift;
			;;
		--verbose|-v)
			VERBOSE=1
			shift;
			;;
		--no-cache|-c)
			USECACHE="no"
			shift;
			;;
		--user|-u)
			CHRUSER=$2;
			shift; shift;
			;;
		--group|-g)
			GROUP=$2;
			shift; shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

DISTRO=$1
DST=$2

if [ $UID != 0 ]; then
	echo "Superuser permissions required. Aborting."
	exit 1
fi;

if [ ! -x $DEBOOTSTRAP ]; then
	echo "deboostrap required but no installed."
	echo "Try 'apt-get install debootstrap'"
	exit 1
fi;

if [ "$1" == "" ]; then
	if [ -r /etc/lsb-release ]; then
		. /etc/lsb-release
		DISTRO=$DISTRIB_CODENAME
		echo "Using current distribution: \"$DISTRIB_ID $DISTRO\"" 
	else
		echo "Using default distribution: \"Ubuntu hardy\""
		DISTRO=hardy
	fi;
fi;

if [ "$2" == "" ]; then
	DST=/var/chroot
	echo "Using default chroot target: \"$DST/$DISTRO\"" 
fi;

case $DISTRO in
	"intrepid"|"hardy"|"gutsy"|"feisty"|"dapper")
		echo "Using a ubuntu distribution"
		;;
	"lenny"|"sarge"|"sid"|"unstable")
		echo "Using a debian distribution"
		;;
	*)
		echo "Unknown distribution: \"$DISTRO\". Aborting."
		;;
esac;

CHRDST=$DST/$DISTRO

echo "Creating $DISTRO chroot in $CHRDST."

if [ -d $CHRDST ]; then
	echo "Target already exists. Aborting."
	exit 1
fi

check_dir $CHRDST

PACKAGES=$CHRDST/var/cache/apt/archives
CACHE=$DST/packages/$DISTRO

if [ $USECACHE == "yes" ]; then
	if [ -d $CACHE ]; then
		check_dir $PACKAGES
		rsync --progress $CACHE/*.deb $PACKAGES
	fi;
fi;

debootstrap $DISTRO $CHRDST $MIRROR 

echo "Updating deb package cache"
check_dir $CACHE
rsync --progress $PACKAGES/*.deb $CACHE

echo "Copying extra system files into chroot."

HOMEDIR=$CHRDST/$HOME


ETCDIR=$CHRDST/etc

check_dir $HOMEDIR
check_dir $ETCDIR

echo "$DISTRO-chroot" > $ETCDIR/debian_chroot

FILES="passwd shadow group sudoers hosts"

for i in $FILES; do
	cp /etc/$i $ETCDIR
done;

# Set some defaults for nice login
if [ -f $HOME/.bashrc ]; then
	cp $HOME/.bashrc $HOMEDIR
fi;

chown -R $CHRUSER:$CHRGROUP $HOMEDIR


# Enable extra sources in the apt sources.list
if [ "$DISTRO" == "hardy" ]; then
   echo "Enabling universe and multiverse for ubuntu."
   echo "deb $MIRROR $DISTRO universe multiverse" >> $ETCDIR/apt/sources.list
fi;

# Post install
CHRTAG="$DISTRO $CHRDST $CHRUSER"

echo $CHRTAG >> $HOME/.chroots
chown $CHRUSER:$CHRGROUP $HOME/.chroots
