#!/bin/bash

CONF="$HOME/.chroots"

function usage {
NAME=`echo $1 | sed -e "s/\.\///g"`

	cat << EOF
 $NAME list
 Usage example: $NAME list

OPTIONS:
  -h, --help    Show this message
EOF
}

# Begin program

case "$1" in
	--help|-h)
		usage $0
		exit 0
		;;
esac

if [ ! -r $CONF ]; then
	exit 0
fi;

NL=`cat $CONF | grep -v "^#" | wc -l`

echo "total $NL"

let i=0
while read line; do
	T=`echo $line | grep -v "^#"`
	if [ "$T" == "" ]; then
		continue;
	fi;
	let i=$i+1
	echo "$i: $line"
done < "$CONF"

exit 0
