#!/bin/bash

CHRTARGET=/var/chroot/hardy
CHRUSER=root
VERBOSE=0

function usage {

NAME=`echo $1 | sed -e "s/\.\///g"`

	cat << EOF
 $NAME [target] [OPTIONS]"
 Usage example: $NAME hardy /var/chroot/test-hardy"

  Login to the specified chroot.  A username can be specified.

OPTIONS:
  -h, --help      Show this message
  -v, --verbose   Verbose [Not implemented]
  -u, --username  Use a specific username to login

EOF
exit 0
}

OPTS="+vh"
LONGOPTS="verbose,help"
TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

eval set -- "$TEMP"

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true; do
	case "$1" in
		--help|-h)
			usage $0;
			exit 0;
			shift;
			;;
		--verbose|-v)
			VERBOSE=1
			shift;
			;;
		--username|-u);
			CHRUSER=$2
			shift;shift;
			break;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;


if [ $UID != 0 ]; then
	echo "Superuser permissions required. Aborting."
	exit 1
fi;


# Determine chroot to use

if [ "$1" != "" ]; then
	CHRTARGET=$1
fi;


# Check if correctly mounted


# Login

echo "Loging in to $CHRUSER@$CHRTARGET"

chroot $CHRTARGET /bin/su - $CHRUSER
