#!/bin/bash

DISTRO=$1
DST=$2

SOURCE="http://de.archive.ubuntu.com/ubuntu"

# Binary files

DEBOOTSTRAP=/usr/sbin/debootstrap

function usage {
	cat << EOF
 $0 [distribution destination]"
 Usage example: $0 hardy /var/chroot/test-hardy"

OPTIONS:
  -h, --help    Show this message
  -v, --verbose Verbose [Not implemented]

EOF
}

function check_dir {
	DIR=$1
	echo "Checking $DIR"
	if [ ! -d $DIR ]; then
		echo "$DIR does not exist. Creating it."
		mkdir -p $DIR
		if [ $? != 0 ]; then
			echo "error creating $DIR. Aborting"
			exit 1
		fi;
	fi;
}


# Begin program

OPTS="v"
LONGOPTS="verbose"

TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

eval set -- "$TEMP"

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true; do
	case "$1" in
		--help|-h)
			echo "Help";
			shift;
			;;
		-v|--verbose)
			echo "Verbose mode on";
			shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

for arg in $@; do echo "--""$arg"; done

exit

if [ $UID != 0 ]; then
	echo "Superuser permissions required. Aborting."
	exit 1
fi;

if [ ! -x $DEBOOTSTRAP ]; then
	echo "deboostrap required but no installed."
	echo "Try 'apt-get install debootstrap'"
	exit 1
fi;

if [ "$1" == "" ]; then
	if [ -r /etc/lsb-release ]; then
		. /etc/lsb-release
		DISTRO=$DISTRIB_CODENAME
		echo "Using current distribution: \"$DISTRIB_ID $DISTRO\"" 
	else
		echo "Using default distribution: \"Ubuntu hardy\""
		DISTRO=hardy
	fi;
fi;

if [ "$2" == "" ]; then
	DST=/var/chroot
	echo "Using default chroot target: \"$DST/$DISTRO\"" 
fi;

case $DISTRO in
	"intrepid"|"hardy"|"gutsy"|"feisty"|"dapper")
		echo "Using a ubuntu distribution"
		;;
	"lenny"|"sarge"|"sid"|"unstable")
		echo "Using a debian distribution"
		;;
	*)
		echo "Unknown distribution: \"$DISTRO\". Aborting."
		;;
esac;

echo "Creating $DISTRO chroot in $DST/$DISTRO."

CHRDST=$DST/$DISTRO

if [ -d $CHRDST ]; then
	echo "Target already exists. Aborting."
	exit 1
fi

check_dir $CHRDST

PACKAGES=$CHRDST/var/cache/apt/archives
CACHE=$DST/packages/$DISTRO

if [ -d $CACHE ]; then
	check_dir $PACKAGES
	cp $CACHE/*.deb $PACKAGES
fi;

debootstrap $DISTRO $CHRDST $SOURCE 

echo "Updating deb package cache"
check_dir $CACHE
rsync --progress $PACKAGES/*.deb $CACHE

echo "Copying extra system files into chroot."

HOMEDIR=$CHRDST/home/alfmatos
ETCDIR=$CHRDST/etc

check_dir $HOMEDIR
check_dir $ETCDIR

echo "$DISTRO-chroot" > $ETCDIR/debian_chroot

FILES="passwd shadow group sudoers hosts"

for i in $FILES; do
	cp /etc/$i $ETCDIR
done;

#chown $USER:$GROUP $HOMEDIR
#if [ -f /home/$USER/.bash_rc ]; then
#	cp /home/$USER/.bashrc $HOMEDIR
#fi;

# Enable extra sources in the apt sources.list

if [ "$DISTRO" == "hardy" ]; then
   echo "Enabling universe and multiverse for ubuntu."
   echo "deb $SOURCE $DISTRO universe multiverse" >> $ETCDIR/apt/sources.list
fi;
