#!/bin/bash

CONF="$HOME/.chroots"

CHECK=0
CLEAN=0

function usage {
NAME=`echo $1 | sed -e "s/\.\///g"`

	cat << EOF
 $NAME list
 Usage example: $NAME list

OPTIONS:
  -h, --help           Show this message
  -v, --verbose        Verbose mode
  -c, --check          Check the validity of listed chroots
  -C, --clean          Remove failed chroots
EOF
}

# Begin program

OPTS="vhcC"
LONGOPTS="verbose,help,check,clean"

TEMP=`getopt -o $OPTS --long $LONGOPTS -- "$@"`

eval set -- "$TEMP"

if [ $? != 0 ] ; then echo "Terminating..." >&2 ; exit 1 ; fi

while true;  do
	case "$1" in
		--help|-h)
			usage $0
			exit 0
			;;
		--check|-c)
			CHECK=1
			echo "Checking valid chroots"
			shift;
			;;
		--clean|-C)
			CLEAN=1
			echo "Removing any failed chroots"
			shift;
			;;
		--)
			shift;
			break;
			;;
		*)
			echo "Error parsing options";
			exit 1;
			;;
	esac
done;

if [ ! -r $CONF ]; then
	exit 0
fi;

NL=`cat $CONF | grep -v "^#" | wc -l`

echo "total $NL"

echo "#  Name   Path   Distro   Default user"

let i=0
while read line; do
	T=`echo $line | grep -v "^#"`
	if [ "$T" == "" ]; then
		continue;
	fi;
	let i=$i+1
	echo "$i: $line"
done < "$CONF"

exit 0
